version: '3.8'

services:
  backend:
    build: .
    container_name: sanatorio_backend
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DB: SanatorioTuSal
